export enum UserActionTypes {
    SET_USERS = 'SET_USERS',
    SET_SELECTED_USER_ID = 'SET_SELECTED_USER_ID',
    SET_IS_NEED_LOAD_DATA = 'SET_IS_NEED_LOAD_DATA',
    SET_IS_OPEN_USER_INFO = 'SET_IS_OPEN_USER_INFO',
    SET_USER_LIST_SEARCH_INPUT_VALUE = 'SET_USER_LIST_SEARCH_INPUT_VALUE',
}